"""add property_type and zip_code

Revision ID: 0829b34b3f4d
Revises: 1a2b3c4d5e6f
Create Date: 2026-06-16 17:31:44.700229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0829b34b3f4d'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BOARDING_HOUSE', sa.Column('property_type', sa.String(length=100), nullable=True))
    op.add_column('LOCATION', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.alter_column('USERS', 'account_setup_complete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USERS', 'account_setup_complete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('LOCATION', 'zip_code')
    op.drop_column('BOARDING_HOUSE', 'property_type')
    # ### end Alembic commands ###
