"""add_viewings_table

Revision ID: 1dd93deb66a7
Revises: abc1234def56
Create Date: 2026-06-18 14:46:56.586487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1dd93deb66a7'
down_revision: Union[str, Sequence[str], None] = 'abc1234def56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VIEWINGS',
    sa.Column('viewing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('viewing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VIEWINGS')
    # ### end Alembic commands ###
