"""add auth_provider to users

Revision ID: 275382b2f368
Revises: 0829b34b3f4d
Create Date: 2026-06-17 15:38:12.377328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275382b2f368'
down_revision: Union[str, Sequence[str], None] = '0829b34b3f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('auth_provider', sa.Enum('email', 'google', 'both'), server_default='email', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'auth_provider')
    # ### end Alembic commands ###
