"""add_street_to_users

Revision ID: 2e78b3fd89a7
Revises: 39b93940384d
Create Date: 2026-06-04 13:20:03.278879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e78b3fd89a7'
down_revision: Union[str, Sequence[str], None] = '39b93940384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('street', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'street')
    # ### end Alembic commands ###
