"""add_date_of_birth_to_users

Revision ID: 39b93940384d
Revises: 
Create Date: 2026-06-03 17:01:07.612978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39b93940384d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ADMIN_LOGS_target_id'), 'ADMIN_LOGS', ['target_id'], unique=False)
    op.create_index(op.f('ix_ADMIN_LOGS_target_type'), 'ADMIN_LOGS', ['target_type'], unique=False)
    op.alter_column('LOCATION', 'province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('LOCATION', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('LOCATION', 'barangay',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_PHOTOS_entity_id'), 'PHOTOS', ['entity_id'], unique=False)
    op.create_index(op.f('ix_PHOTOS_entity_type'), 'PHOTOS', ['entity_type'], unique=False)
    op.add_column('REPORTS', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.add_column('REPORTS', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_report_target'), table_name='REPORTS')
    op.create_index(op.f('ix_REPORTS_target_id'), 'REPORTS', ['target_id'], unique=False)
    op.create_index(op.f('ix_REPORTS_target_type'), 'REPORTS', ['target_type'], unique=False)
    op.create_foreign_key(None, 'REPORTS', 'USERS', ['resolved_by'], ['user_id'], ondelete='SET NULL')
    op.alter_column('REVIEWS', 'rating',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('USERS', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('USERS', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'USERS', 'LOCATION', ['location_id'], ['location_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USERS', type_='foreignkey')
    op.drop_column('USERS', 'date_of_birth')
    op.drop_column('USERS', 'location_id')
    op.alter_column('REVIEWS', 'rating',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'REPORTS', type_='foreignkey')
    op.drop_index(op.f('ix_REPORTS_target_type'), table_name='REPORTS')
    op.drop_index(op.f('ix_REPORTS_target_id'), table_name='REPORTS')
    op.create_index(op.f('idx_report_target'), 'REPORTS', ['target_type', 'target_id'], unique=False)
    op.drop_column('REPORTS', 'resolved_at')
    op.drop_column('REPORTS', 'resolved_by')
    op.drop_index(op.f('ix_PHOTOS_entity_type'), table_name='PHOTOS')
    op.drop_index(op.f('ix_PHOTOS_entity_id'), table_name='PHOTOS')
    op.alter_column('LOCATION', 'barangay',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('LOCATION', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('LOCATION', 'province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_ADMIN_LOGS_target_type'), table_name='ADMIN_LOGS')
    op.drop_index(op.f('ix_ADMIN_LOGS_target_id'), table_name='ADMIN_LOGS')
    # ### end Alembic commands ###
