"""add_verification_code_and_reset_code_to_users

Revision ID: 702be4da7b51
Revises: f811ddf5b1a8
Create Date: 2026-06-14 06:40:28.725115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '702be4da7b51'
down_revision: Union[str, Sequence[str], None] = 'f811ddf5b1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TOKEN_BLACKLIST',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TOKEN_BLACKLIST_jti'), 'TOKEN_BLACKLIST', ['jti'], unique=True)
    op.create_table('MAINTENANCE_REQUESTS',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column('USERS', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('USERS', sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
    op.add_column('USERS', sa.Column('reset_code_hash', sa.String(length=128), nullable=True))
    op.drop_column('USERS', 'reset_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('reset_code', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('USERS', 'reset_code_hash')
    op.drop_column('USERS', 'verification_code_expires')
    op.drop_column('USERS', 'verification_code')
    op.drop_table('MAINTENANCE_REQUESTS')
    op.drop_index(op.f('ix_TOKEN_BLACKLIST_jti'), table_name='TOKEN_BLACKLIST')
    op.drop_table('TOKEN_BLACKLIST')
    # ### end Alembic commands ###
