"""add_reset_code_to_users

Revision ID: 8d1933cf7fb1
Revises: d35ef4c39b41
Create Date: 2026-06-13 23:17:49.401002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1933cf7fb1'
down_revision: Union[str, Sequence[str], None] = 'd35ef4c39b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('reset_code', sa.String(length=6), nullable=True))
    op.add_column('USERS', sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'reset_code_expires')
    op.drop_column('USERS', 'reset_code')
    # ### end Alembic commands ###
