"""recreate all tables

Revision ID: d35ef4c39b41
Revises: 2e78b3fd89a7
Create Date: 2026-06-05 12:21:38.889434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35ef4c39b41'
down_revision: Union[str, Sequence[str], None] = '2e78b3fd89a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AMENITIES',
    sa.Column('amenity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amenity_name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    op.create_table('LOCATION',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('PHOTOS',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('listing', 'room'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_PHOTOS_entity_id'), 'PHOTOS', ['entity_id'], unique=False)
    op.create_index(op.f('ix_PHOTOS_entity_type'), 'PHOTOS', ['entity_type'], unique=False)
    op.create_table('USERS',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'owner', 'admin'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('id_document_url', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'banned', 'suspended'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['LOCATION.location_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ADMIN_LOGS',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('listing', 'user', 'report', 'booking'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_ADMIN_LOGS_target_id'), 'ADMIN_LOGS', ['target_id'], unique=False)
    op.create_index(op.f('ix_ADMIN_LOGS_target_type'), 'ADMIN_LOGS', ['target_type'], unique=False)
    op.create_table('BOARDING_HOUSE',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('bh_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'banned'), nullable=True),
    sa.Column('bh_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('permit_url', sa.String(length=255), nullable=True),
    sa.Column('min_stay_months', sa.Integer(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['LOCATION.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('NOTIFICATIONS',
    sa.Column('notif_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('booking', 'review', 'system', 'favorite'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['USERS.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('REPORTS',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.Enum('listing', 'user', 'review', 'booking'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'resolved', 'dismissed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['USERS.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_id'], ['USERS.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_REPORTS_target_id'), 'REPORTS', ['target_id'], unique=False)
    op.create_index(op.f('ix_REPORTS_target_type'), 'REPORTS', ['target_type'], unique=False)
    op.create_table('FAVORITES',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('LISTING_AMENITIES',
    sa.Column('lm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['AMENITIES.amenity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lm_id')
    )
    op.create_table('ROOMS',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_month', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('floor_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('BOOKINGS',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'cancelled'), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['ROOMS.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('BOOKING_HISTORY',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('active', 'pending', 'cancelled'), nullable=True),
    sa.Column('new_status', sa.Enum('active', 'pending', 'cancelled'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['BOOKINGS.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['USERS.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('PAYMENTS',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.Enum('gcash', 'bank_transfer', 'cash', 'card'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded'), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BOOKINGS.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('REVIEWS',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BOOKINGS.booking_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['BOARDING_HOUSE.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('REVIEWS')
    op.drop_table('PAYMENTS')
    op.drop_table('BOOKING_HISTORY')
    op.drop_table('BOOKINGS')
    op.drop_table('ROOMS')
    op.drop_table('LISTING_AMENITIES')
    op.drop_table('FAVORITES')
    op.drop_index(op.f('ix_REPORTS_target_type'), table_name='REPORTS')
    op.drop_index(op.f('ix_REPORTS_target_id'), table_name='REPORTS')
    op.drop_table('REPORTS')
    op.drop_table('NOTIFICATIONS')
    op.drop_table('BOARDING_HOUSE')
    op.drop_index(op.f('ix_ADMIN_LOGS_target_type'), table_name='ADMIN_LOGS')
    op.drop_index(op.f('ix_ADMIN_LOGS_target_id'), table_name='ADMIN_LOGS')
    op.drop_table('ADMIN_LOGS')
    op.drop_table('USERS')
    op.drop_index(op.f('ix_PHOTOS_entity_type'), table_name='PHOTOS')
    op.drop_index(op.f('ix_PHOTOS_entity_id'), table_name='PHOTOS')
    op.drop_table('PHOTOS')
    op.drop_table('LOCATION')
    op.drop_table('AMENITIES')
    # ### end Alembic commands ###
