"""add_email_verification_to_users

Revision ID: f811ddf5b1a8
Revises: 8d1933cf7fb1
Create Date: 2026-06-14 00:14:45.725396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f811ddf5b1a8'
down_revision: Union[str, Sequence[str], None] = '8d1933cf7fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('USERS', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.add_column('USERS', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'verification_token_expires')
    op.drop_column('USERS', 'verification_token')
    op.drop_column('USERS', 'email_verified')
    # ### end Alembic commands ###
